# Step 1. Business problem understanding
Pridict Salary of a person based on input variable.

In [1]:
import numpy as np
import pandas as pd 

# Step 2. Data Understanding.
load data and understand every varible.

In [3]:
data_set = pd.read_csv("hiring.csv")

In [4]:
data_set

experience  test_score  interview_score  salary
0           1           8                9   50000
1           1           8                6   45000
2           5           6                7   60000
3           2          10               10   65000
4           7           9                6   70000
5           3           7               10   62000
6          10           7                7   72000
7          11           7                8   80000

In [5]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   experience       8 non-null      int64
 1   test_score       8 non-null      int64
 2   interview_score  8 non-null      int64
 3   salary           8 non-null      int64
dtypes: int64(4)
memory usage: 384.0 bytes


In [6]:
data_set.info()

experience  test_score  interview_score  salary
0       False       False            False   False
1       False       False            False   False
2       False       False            False   False
3       False       False            False   False
4       False       False            False   False
5       False       False            False   False
6       False       False            False   False
7       False       False            False   False

In [7]:
data_set.isnull().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

# Step 3. Data Preprocessing.
Data cleaning

In [8]:
data_set["experience"].fillna(0, inplace=True)

In [9]:
data_set["test_score"].fillna(data_set["test_score"].mean(),inplace=True)

In [10]:
data_set

experience  test_score  interview_score  salary
0           1           8                9   50000
1           1           8                6   45000
2           5           6                7   60000
3           2          10               10   65000
4           7           9                6   70000
5           3           7               10   62000
6          10           7                7   72000
7          11           7                8   80000

In [25]:
data_set.shape

(8, 4)

In [60]:
X=data_set.drop("salary",axis=1)
y=data_set["salary"]

# Modeling

In [61]:
from sklearn.linear_model import LinearRegression

In [74]:
lr_model = LinearRegression()

In [84]:
lr_model.fit(X_train, y_train)  #Fitting model train data

LinearRegression()

In [77]:
lr_model.coef_

array([3221.66920797, 2682.0391841 , 2034.92620616])

In [78]:
lr_model.intercept_

9654.506746454157

In [79]:
lr_model.predict([[2, 9, 6]])

C:\Users\ajitm\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52445.75505624])

In [80]:
import pickle

In [81]:
pickle.dump(lr_model,open('model.pkl','wb'))   # Saving model to disk

In [82]:
reg_model = pickle.load(open('model.pkl','rb'))  # Loading model to campare the results

In [85]:
reg_model.predict([[2, 9, 6]])      #campare the results

C:\Users\ajitm\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52445.75505624])